/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_api_admin_devices_get"];
        put?: never;
        /** Create Device */
        post: operations["create_device_api_admin_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/devices/{device_pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Device
         * @description Revocation. The unit gets 401 on its next poll and keeps its last valid
         *     config, per DATA-CONTRACT.md expiry semantics.
         */
        delete: operations["delete_device_api_admin_devices__device_pk__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/devices/{device_pk}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device Config */
        get: operations["get_device_config_api_admin_devices__device_pk__config_get"];
        /**
         * Put Device Config
         * @description Tune, then publish.
         *
         *     Full replace. Missing fields take defaults; unknown fields are an error,
         *     because a typo'd key that silently tuned nothing is a quiet failure.
         *
         *     The saved values are then written to `sites/{site_id}/remote_config.json`,
         *     signed. That blob is the delivery path (D-020) — saving without publishing
         *     would leave the panel showing a configuration no device will ever apply.
         */
        put: operations["put_device_config_api_admin_devices__device_pk__config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index Status
         * @description Drift per site and per day, plus when the pass last ran (R-12.5).
         *
         *     Read-only and cheap: it lists blob *names* and runs one query per site. It
         *     opens no blob and indexes nothing, which is what makes it safe to call from
         *     a panel that refreshes.
         *
         *     Non-zero drift is a fault, not a statistic. It means events exist in storage
         *     that the dashboard will not show — the same failure as a device reporting
         *     itself healthy while deaf, and the reason this is a screen rather than a log
         *     line.
         */
        get: operations["index_status_api_admin_index_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/index/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebuild Index
         * @description Drop this site's index rows and rebuild them from object storage (R-12.2).
         *
         *     **This is the proof that the index is derived.** If a rebuild cannot
         *     reproduce it, then something existed only in Postgres and the index had
         *     quietly become a second source of truth — the exact thing D-021 rules out.
         *     Worth running deliberately every so often, not only when something looks
         *     wrong.
         *
         *     Losing these rows costs a pass, never a detection: object storage is the
         *     record and every row here came from a blob that is still there.
         */
        post: operations["rebuild_index_api_admin_index_rebuild_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/index/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Reconcile
         * @description Run the pass now, for one site or all of them.
         *
         *     Safe to press twice: every write goes through the indexer, which is
         *     idempotent on `event_id` (R-12.3). It does not replace the timer — it exists
         *     so somebody investigating drift can act on it without waiting a day.
         */
        post: operations["run_reconcile_api_admin_index_reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sites Admin */
        get: operations["list_sites_admin_api_admin_sites_get"];
        put?: never;
        /** Create Site */
        post: operations["create_site_api_admin_sites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Sites
         * @description Seed the table from `_sites.json`. Explicit, never automatic — see
         *     services/sites.py for why.
         */
        post: operations["import_sites_api_admin_sites_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sites/{site_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Site
         * @description `site_id` itself is immutable: it is a storage path segment, and renaming
         *     it would orphan every event, clip and rollup already written under it.
         */
        put: operations["update_site_api_admin_sites__site_id__put"];
        post?: never;
        /**
         * Delete Site
         * @description Refuses while anything still points at it. Deleting a site out from under
         *     a device would leave a credential valid for a site that does not exist.
         */
        delete: operations["delete_site_api_admin_sites__site_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Sites */
        put: operations["set_sites_api_admin_users__user_id__sites_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Device Config
         * @description **Read-only debugging view of the configuration blob** (D-020).
         *
         *     This is not the delivery path. The device reads
         *     `sites/{site_id}/remote_config.json` from storage, which the backend writes
         *     when configuration is tuned. This route exists so an operator can see what a
         *     unit will receive without opening a storage browser, and it returns the blob
         *     **byte for byte** — reading it here and reading it from storage must never
         *     produce two different documents, because that is how a signature mismatch
         *     hides.
         *
         *     It deliberately does not compose a document of its own. If the blob is
         *     absent, that is the honest answer: nothing has been published for this site.
         */
        get: operations["device_config_api_devices_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push Event
         * @description **One detection, pushed by the device as it happens** (R-6.3, D-022).
         *
         *     This is the low-latency path and nothing more. The device writes the event
         *     blob regardless of what happens here, so a failure costs freshness and never
         *     an event: the weekly reconcile pass reads the same event out of storage. Any
         *     change that makes correctness depend on this route has broken the design —
         *     see `DATA-CONTRACT.md`, **Event upload**.
         *
         *     **`202` whether or not the event was already indexed.** A duplicate is the
         *     expected case, not an error: a reconcile pass may have picked the event up
         *     first, or the device may be retrying after an ambiguous timeout. Returning
         *     `409` would push the device into tracking what it had successfully sent,
         *     which is exactly the bookkeeping the unique constraint on `event_id` exists
         *     to make unnecessary (R-12.3). There is no `409` on this route.
         *
         *     The document is stored verbatim. No `response_model`, no reshaping, no
         *     validation beyond the handful of fields the index sorts and filters on — a
         *     field the device adds must reach the browser, not be quietly dropped on the
         *     way in, which is the same rule the rollup routes follow.
         */
        post: operations["push_event_api_devices_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sites
         * @description Only the sites this user may see. The list itself is a permission boundary.
         */
        get: operations["sites_api_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/acoustic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Acoustic */
        get: operations["acoustic_api_sites__site_id__acoustic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/clips/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clip
         * @description Audio proxied through the API, so the container stays private (R-5.4).
         */
        get: operations["clip_api_sites__site_id__clips__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Paginated and filtered. The browser gets a page, never the history (R-5.1).
         *
         *     Served from the derived index, so this costs one query and no reads against
         *     object storage regardless of the window (D-021, R-12.1).
         */
        get: operations["events_api_sites__site_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/ocean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ocean */
        get: operations["ocean_api_sites__site_id__ocean_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/power": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Power */
        get: operations["power_api_sites__site_id__power_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites/{site_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status__api_sites__site_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DeviceConfigOut */
        DeviceConfigOut: {
            /**
             * Clamp Notes
             * @default []
             */
            clamp_notes: string[];
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Config Version */
            config_version: string;
            /** Device Id */
            device_id: string;
            /** Is Default */
            is_default: boolean;
            /** Publish Warning */
            publish_warning?: string | null;
            /** Published To */
            published_to?: string | null;
            /** Site Id */
            site_id: string;
            /** Updated Utc */
            updated_utc: string | null;
            /** Version */
            version: number;
        };
        /** DeviceCreated */
        DeviceCreated: {
            /** Active */
            active: boolean;
            /** Device Id */
            device_id: string;
            /** Id */
            id: number;
            /** Key */
            key: string;
            /** Last Seen */
            last_seen: string | null;
            /** Site Id */
            site_id: string;
        };
        /** DeviceIn */
        DeviceIn: {
            /** Device Id */
            device_id: string;
            /** Site Id */
            site_id: string;
        };
        /** DeviceOut */
        DeviceOut: {
            /** Active */
            active: boolean;
            /** Device Id */
            device_id: string;
            /** Id */
            id: number;
            /** Last Seen */
            last_seen: string | null;
            /** Site Id */
            site_id: string;
        };
        /** EventsPage */
        EventsPage: {
            /** Has More */
            has_more: boolean;
            /** Index Updated Utc */
            index_updated_utc?: string | null;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Storage */
            storage: string;
        };
        /** IndexDayOut */
        IndexDayOut: {
            /** Blobs In Storage */
            blobs_in_storage: number;
            /** Day */
            day: string;
            /** Drift */
            drift: number;
            /** Indexed */
            indexed: number;
        };
        /** IndexSiteOut */
        IndexSiteOut: {
            /** Blobs In Storage */
            blobs_in_storage: number;
            /** Days With Drift */
            days_with_drift: components["schemas"]["IndexDayOut"][];
            /** Drift */
            drift: number;
            /** Indexed */
            indexed: number;
            /** Last Run Error */
            last_run_error?: string | null;
            /** Last Run Ok */
            last_run_ok?: boolean | null;
            /** Last Run Trigger */
            last_run_trigger?: string | null;
            /** Last Run Utc */
            last_run_utc?: string | null;
            /** Since */
            since: string;
            /** Site Id */
            site_id: string;
            /** Until */
            until: string;
            /** Window Days */
            window_days: number;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Me */
        Me: {
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Sites */
            sites: string[];
        };
        /** Ok */
        Ok: {
            /** Ok */
            ok: boolean;
        };
        /** RebuildIn */
        RebuildIn: {
            /** Confirm Site Id */
            confirm_site_id: string;
            /** Site Id */
            site_id: string;
        };
        /** ReconcileOut */
        ReconcileOut: {
            /** Conflicting */
            conflicting: number;
            /** Drift */
            drift: number;
            /** Error */
            error?: string | null;
            /** Newly Indexed */
            newly_indexed: number;
            /** Ok */
            ok: boolean;
            /** Rejected */
            rejected: number;
            /** Site Id */
            site_id: string;
        };
        /** SiteIn */
        SiteIn: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Device */
            device?: string | null;
            /** Id */
            id: string;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Name */
            name: string;
        };
        /** SiteUpdate */
        SiteUpdate: {
            /** Active */
            active?: boolean | null;
            /** Device */
            device?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Name */
            name?: string | null;
        };
        /** SitesIn */
        SitesIn: {
            /** Sites */
            sites: string[];
        };
        /** UserIn */
        UserIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default operator
             */
            role: string;
            /**
             * Sites
             * @default []
             */
            sites: string[];
        };
        /** UserOut */
        UserOut: {
            /** Active */
            active: boolean;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Sites */
            sites: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** SitesOut */
        app__routers__admin__SitesOut: {
            /** Sites */
            sites: {
                [key: string]: unknown;
            }[];
            /** Source */
            source: string;
        };
        /** SitesOut */
        app__routers__data__SitesOut: {
            /** Sites */
            sites: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_devices_api_admin_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceOut"][];
                };
            };
        };
    };
    create_device_api_admin_devices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_api_admin_devices__device_pk__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_config_api_admin_devices__device_pk__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_device_config_api_admin_devices__device_pk__config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_status_api_admin_index_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexSiteOut"][];
                };
            };
        };
    };
    rebuild_index_api_admin_index_rebuild_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RebuildIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_reconcile_api_admin_index_reconcile_post: {
        parameters: {
            query?: {
                site_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sites_admin_api_admin_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__routers__admin__SitesOut"];
                };
            };
        };
    };
    create_site_api_admin_sites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_sites_api_admin_sites_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__routers__admin__SitesOut"];
                };
            };
        };
    };
    update_site_api_admin_sites__site_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_site_api_admin_sites__site_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_sites_api_admin_users__user_id__sites_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SitesIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    device_config_api_devices_config_get: {
        parameters: {
            query?: never;
            header: {
                "x-device-key": string;
                "x-device-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_event_api_devices_events_post: {
        parameters: {
            query?: never;
            header: {
                "x-device-key": string;
                "x-device-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    sites_api_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__routers__data__SitesOut"];
                };
            };
        };
    };
    acoustic_api_sites__site_id__acoustic_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clip_api_sites__site_id__clips__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_sites__site_id__events_get: {
        parameters: {
            query?: {
                since?: string | null;
                until?: string | null;
                event_type?: string | null;
                min_score?: number;
                include_suppressed?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ocean_api_sites__site_id__ocean_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    power_api_sites__site_id__power_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status__api_sites__site_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                site_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
