"""indexer run audit

Revision ID: 3f3ca891ece9
Revises: 7181aa249c3c
Create Date: 2026-09-03 11:45:19.363798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel autogenerate emits sqlmodel.sql.sqltypes.* for str columns but does
# not import the module. Without this line every generated migration fails with
# NameError at upgrade time.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f3ca891ece9'
down_revision: Union[str, None] = '7181aa249c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexer_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('blobs_in_storage', sa.Integer(), nullable=False),
    sa.Column('newly_indexed', sa.Integer(), nullable=False),
    sa.Column('conflicting', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('drift', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexer_run_site_id'), 'indexer_run', ['site_id'], unique=False)
    op.create_index(op.f('ix_indexer_run_started_utc'), 'indexer_run', ['started_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexer_run_started_utc'), table_name='indexer_run')
    op.drop_index(op.f('ix_indexer_run_site_id'), table_name='indexer_run')
    op.drop_table('indexer_run')
    # ### end Alembic commands ###
