"""device push health

Revision ID: 7181aa249c3c
Revises: 7deafd5e87df
Create Date: 2026-09-03 10:54:49.392134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel autogenerate emits sqlmodel.sql.sqltypes.* for str columns but does
# not import the module. Without this line every generated migration fails with
# NameError at upgrade time.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7181aa249c3c'
down_revision: Union[str, None] = '7deafd5e87df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('last_push_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('device', sa.Column('last_push_error_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('device', sa.Column('last_push_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'last_push_error')
    op.drop_column('device', 'last_push_error_utc')
    op.drop_column('device', 'last_push_utc')
    # ### end Alembic commands ###
