"""detection events index

Revision ID: 7deafd5e87df
Revises: 6d1fd7886f57
Create Date: 2026-08-26 15:45:59.634701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel autogenerate emits sqlmodel.sql.sqltypes.* for str columns but does
# not import the module. Without this line every generated migration fails with
# NameError at upgrade time.
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7deafd5e87df'
down_revision: Union[str, None] = '6d1fd7886f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('indexed_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_via', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detection_event_captured', 'detection_event', ['captured_utc'], unique=False)
    op.create_index(op.f('ix_detection_event_detector'), 'detection_event', ['detector'], unique=False)
    op.create_index(op.f('ix_detection_event_event_id'), 'detection_event', ['event_id'], unique=True)
    op.create_index(op.f('ix_detection_event_event_type'), 'detection_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_detection_event_first_seen_via'), 'detection_event', ['first_seen_via'], unique=False)
    op.create_index('ix_detection_event_site_captured', 'detection_event', ['site_id', 'captured_utc'], unique=False)
    op.create_index(op.f('ix_detection_event_site_id'), 'detection_event', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_event_site_id'), table_name='detection_event')
    op.drop_index('ix_detection_event_site_captured', table_name='detection_event')
    op.drop_index(op.f('ix_detection_event_first_seen_via'), table_name='detection_event')
    op.drop_index(op.f('ix_detection_event_event_type'), table_name='detection_event')
    op.drop_index(op.f('ix_detection_event_event_id'), table_name='detection_event')
    op.drop_index(op.f('ix_detection_event_detector'), table_name='detection_event')
    op.drop_index('ix_detection_event_captured', table_name='detection_event')
    op.drop_table('detection_event')
    # ### end Alembic commands ###
