"""device silence alerts

Revision ID: 9c2ab4e17d05
Revises: 3f3ca891ece9
Create Date: 2026-09-03 12:20:00.000000

**Written by hand, not autogenerated**, because the Docker daemon was down when
the model landed and `make migrate` runs inside the container.

**Verified 2026-09-03**: applied to Postgres, then `make migrate` was run against
the resulting schema and autogenerated an empty `upgrade()` — meaning this file
and the model agree. The verification stub was deleted. If you touch
`DeviceAlert`, generate the next revision properly rather than editing this one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel autogenerate emits sqlmodel.sql.sqltypes.* for str columns but does
# not import the module. Without this line every generated migration fails with
# NameError at upgrade time.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c2ab4e17d05'
down_revision: Union[str, None] = '3f3ca891ece9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'device_alert',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('opened_utc', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_seen_utc', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cleared_utc', sa.DateTime(timezone=True), nullable=True),
        sa.Column('notified_utc', sa.DateTime(timezone=True), nullable=True),
        sa.Column('notify_count', sa.Integer(), nullable=False),
        sa.Column('notify_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_device_alert_site_id'), 'device_alert', ['site_id'],
                    unique=False)
    op.create_index(op.f('ix_device_alert_kind'), 'device_alert', ['kind'],
                    unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_device_alert_kind'), table_name='device_alert')
    op.drop_index(op.f('ix_device_alert_site_id'), table_name='device_alert')
    op.drop_table('device_alert')
