"""initial schema

Revision ID: cbb4417fdbec
Revises: 
Create Date: 2026-08-21 11:13:26.729005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel autogenerate emits sqlmodel.sql.sqltypes.* for str columns but does
# not import the module. Without this line every generated migration fails with
# NameError at upgrade time.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbb4417fdbec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_device_id'), 'device', ['device_id'], unique=True)
    op.create_index(op.f('ix_device_site_id'), 'device', ['site_id'], unique=False)
    op.create_table('deviceconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_utc', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deviceconfig_device_id'), 'deviceconfig', ['device_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('siteaccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siteaccess_site_id'), 'siteaccess', ['site_id'], unique=False)
    op.create_index(op.f('ix_siteaccess_user_id'), 'siteaccess', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siteaccess_user_id'), table_name='siteaccess')
    op.drop_index(op.f('ix_siteaccess_site_id'), table_name='siteaccess')
    op.drop_table('siteaccess')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_deviceconfig_device_id'), table_name='deviceconfig')
    op.drop_table('deviceconfig')
    op.drop_index(op.f('ix_device_site_id'), table_name='device')
    op.drop_index(op.f('ix_device_device_id'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
